[package]
name = "sample-controller"
edition = "2024"

[dependencies]
k8s-openapi = { version = "0.26", features = ["v1_34"] }
kube = { version = "2", features = ["derive"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
